# Generated by Django 3.1.7 on 2021-03-15 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coven', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coven',
            old_name='purchaser',
            new_name='leader',
        ),
    ]
